import {
  BarChart3,
  BookOpen,
  BoxesIcon,
  BoxIcon,
  Briefcase,
  Building,
  Building2,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Crown,
  FileText,
  GraduationCap,
  HelpCircle,
  LayoutDashboardIcon,
  LineChart,
  Loader2,
  LogsIcon,
  LucideIcon,
  LucideProps,
  MenuIcon,
  MessageCircle,
  Moon,
  MoreVertical,
  Package,
  PlusIcon,
  Presentation,
  School,
  Settings,
  SettingsIcon,
  Shield,
  ShoppingCartIcon,
  Star,
  SunMedium,
  TagsIcon,
  Trophy,
  User,
  Users,
  Workflow,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  // Existing icons
  job: Briefcase,
  setting: SettingsIcon,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  settings: Settings,
  billing: CreditCard,
  users: User,
  sun: SunMedium,
  moon: Moon,
  menu: MenuIcon,
  add: PlusIcon,
  tag: TagsIcon,
  dashboard: LayoutDashboardIcon,
  book: BookOpen,
  ellipsis: MoreVertical,
  check: Check,

  // New icons for navigation
  order: ShoppingCartIcon,
  building: Building,
  inventory: BoxIcon,
  assemblies: BoxesIcon,
  picklist: LogsIcon,
};
